### ISSUE TITLE
Keyword in 'head' formula causes error on install

### ISSUE THREAD

**Issue by bbmreed** [codekitchen/homebrew-dinghy#3]
When installing the head version of dinghy via homebrew, we are encountering an error:

```
$ brew install --HEAD dinghy
==> Installing dinghy from codekitchen/dinghy
==> Installing dependencies for codekitchen/dinghy/dinghy: automake
==> Installing codekitchen/dinghy/dinghy dependency: automake
==> Downloading https://homebrew.bintray.com/bottles/automake-1.16.1_1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring automake-1.16.1_1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/automake/1.16.1_1: 131 files, 3.4MB
==> Installing codekitchen/dinghy/dinghy --HEAD
==> Cloning https://github.com/codekitchen/dinghy.git
Updating /Users/mike/Library/Caches/Homebrew/dinghy--git
From https://github.com/codekitchen/dinghy
   05349a3..c7c0a2e  master     -> origin/master
 * [new tag]         v4.6.5     -> v4.6.5
 * [new tag]         v4.6.4     -> v4.6.4
Fetching submodule cli/fsevents_to_vm
From https://github.com/codekitchen/fsevents_to_vm
   eab8080..9a32dbc  master     -> origin/master
==> Checking out branch master
Error: undefined method `to_str' for :master:Symbol
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/system_command.rb:113:in `block in expanded_args'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `map'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `expanded_args'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:71:in `command'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:119:in `each_output_line'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:35:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:23:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:16:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:105:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:871:in `checkout'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:776:in `update'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:128:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:119:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:72:in `stage'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/forwardable.rb:202:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2022:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1117:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:113:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:520:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:110:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:191:in `<main>'
```

I initially filed a bug with homebrew core, but got directed here instead. 

See this comment for more details: https://github.com/Homebrew/homebrew-core/issues/31840#issuecomment-419849751

**Comment by codekitchen** [comment]
That's an odd thing for them to deprecate, but an easy fix. `brew up` and it should work now, thanks for tracking it down.
